spring.application.name=transcendence

# Redis Configuration
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}
spring.redis.database=${REDIS_DATABASE:0}
spring.redis.timeout=${REDIS_TIMEOUT:2000ms}

# Redis Queue Name
redis.queue.name=${REDIS_QUEUE_NAME:email-queue}

# Mail Configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true