services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  usermanagement-service:
    build:
      context: ../..
      dockerfile: infra/docker/dockerfile-usermanagement
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    container_name: usermanagement-service
    depends_on:
      redis:
        condition: service_healthy

  emails-service:
    build:
      context: ../..
      dockerfile: infra/docker/dockerfile-emails-service
    env_file:
      - ../../.env
    ports:
      - "4001:4001"
    restart: unless-stopped
    container_name: emails-service
    depends_on:
      redis:
        condition: service_healthy