FROM redhat/ubi9-minimal:latest

RUN microdnf install -y tar gzip && microdnf clean all

RUN groupadd --gid 1000 logstash && \
    adduser --uid 1000 --gid 1000 \
    --home "/usr/share/logstash" \
    --no-create-home \
    logstash

WORKDIR /usr/share/logstash

RUN arch="$(rpm --query --queryformat='%{ARCH}' rpm)" && \
    curl --fail --location --output logstash.tar.gz https://artifacts.elastic.co/downloads/logstash/logstash-9.2.5-linux-${arch}.tar.gz && \
    tar -zxf logstash.tar.gz --strip-components=1 -C /usr/share/logstash && \
    rm -f logstash.tar.gz && \
    chown -R 1000:1000 /usr/share/logstash

COPY infra/logstash/pipeline/default.conf /usr/share/logstash/pipeline/default.conf

USER 1000

EXPOSE 5000 5044 9600

CMD ["/usr/share/logstash/bin/logstash", "-f", "/usr/share/logstash/pipeline/default.conf"]
